---
title: "4a_desc_sens"
author: "R.Spielhofer"
date: "9 Dezember 2020"
output: html_document
---

```{r setup, include=FALSE}

require(raster)
require(rgdal)
require(dplyr)
require(sf)
require(sp)
require(ggplot2)
require(tmap)
require(tmaptools)
require(DBI)
require(RPostgreSQL)
require(rpostgis)
require(ggpubr)
require(spatstat)
require(rstatix)
require(reticulate)
require(tidyr)
require(maptools)
require(RPostgres)
require(stringr)
require(car)
library(onewaytests)
library(psych)
library(plot3D)
library(pwr)
library(rasterVis)
library(RColorBrewer)
```

# raster for the appendix
```{r}
#install.packages("rasterVis")
# Create list of NDVI file paths
rasterPath <- list.files("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/1_wp/pot_ener_CH", full.names = TRUE, pattern = ".tif$")
rasterNames<- list.files("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/1_wp/pot_ener_CH", full.names = FALSE, pattern = ".tif$")
rasterNames<- gsub(".tif","",rasterNames)

# Create a time series raster stack
raster_stack <- stack(rasterPath)

# apply scale factor

levelplot(raster_stack,
          main="Electricity production",
          layout = c(3,1),
           names.attr=rasterNames,
          scales=list(draw=FALSE ))


airdens<-raster("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/1_wp/200_airdens.gri")
levelplot(airdens,
          main="Air density",
          scales=list(draw=FALSE ))
```


#Load the pareto data
```{r}
cur_dat<-Sys.Date()
pareto<-read.csv("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/3_wp/NSGA3_RES/out/fitness_all_210122.csv", sep=",")


#make the SCENARIOS as factors
pareto$SCEN<-as.factor(pareto$SCEN)
scen_names<-levels(pareto$SCEN)

pareto$RESTRICTION<-as.factor(pareto$RESTRICTION)
res_names<-levels(pareto$RESTRICTION)

pareto$POLICY<-as.factor(pareto$POLICY)
pol_names<-levels(pareto$POLICY)

pareto$MODEL<-as.factor(pareto$MODEL)
mod_names<-levels(pareto$MODEL)
# restrictive scen
tmp_dat<-subset(pareto, pareto$SCEN=="REF"|pareto$SCEN=="ISOS"|pareto$SCEN=="FOR"|pareto$SCEN=="CRF"|pareto$SCEN=="ALL" )

#relaxing scen
#tmp_dat<-subset(pareto, pareto$SCEN=="REF"|pareto$SCEN=="ISOS_CRF"|pareto$SCEN=="FOR_ISOS"|pareto$SCEN=="FOR_CRF"|pareto$SCEN=="ALL")
```

# Sensitivity analysis (effect of Optimization parameter settings)
```{r}

summary(aov(N_WT~MODEL*SCEN,pareto))
eta_squared(aov(N_WT~MODEL+SCEN,pareto))

summary(aov(ENERDENS~MODEL*SCEN,pareto))
eta_squared(aov(ENERDENS~MODEL+SCEN,pareto))

summary(aov(CLUS~MODEL*SCEN,pareto))
eta_squared(aov(CLUS~MODEL+SCEN,pareto))



#graphical check
ggplot(tmp_dat, aes(x=as.factor(MODEL), y=CLUS)) +   
    geom_boxplot()
ggplot(tmp_dat, aes(x=as.factor(MODEL), y=N_WT)) +   
    geom_boxplot()
ggplot(tmp_dat, aes(x=as.factor(MODEL), y=ENERDENS)) +   
    geom_boxplot()

```


#Spatial distribution
```{r}

```

# Boxplot


```{r descriptives}

#descriptive table for appendix
pareto$uni_scen<-paste(pareto$SCEN,pareto$MODEL,sep = "_")
pareto$uni_scen<-as.factor(pareto$uni_scen)
desc<-as.data.frame(describeBy(pareto[,1:3],pareto$uni_scen))

#Tabular form
desc_mw<-describeBy(x=pareto[3],group=pareto$uni_scen, mat = T)
desc_WT<-describeBy(x=pareto[1],group=pareto$uni_scen, mat = T)
desc_clus<-describeBy(x=pareto[2],group=pareto$uni_scen, mat = T)
write.csv(desc_mw, paste("Y:/people/spreto/01_ETH/02_PUBLICATIONS/01_MAIN/3_WIND_OPTIM/Tables/",paste(cur_dat,"mw_desc.csv",sep="_"),sep=""))
write.csv(desc_WT, paste("Y:/people/spreto/01_ETH/02_PUBLICATIONS/01_MAIN/3_WIND_OPTIM/Tables/",paste(cur_dat,"WT_desc.csv",sep="_"),sep=""))
write.csv(desc_clus, paste("Y:/people/spreto/01_ETH/02_PUBLICATIONS/01_MAIN/3_WIND_OPTIM/Tables/",paste(cur_dat,"clus_desc.csv",sep="_"),sep=""))

#######Box plots to explore the data of the three goals for each scenario
clus<-ggplot(pareto, aes(x=as.factor(POLICY), y=CLUS, fill = POLICY)) +   
    geom_boxplot()+
    facet_wrap(~RESTRICTION+MODEL)+
    #theme_light()+
    theme(legend.position = "none")+
    scale_fill_manual(values=c("#FF8000", "#00994D", "#0080ff","#ff33ff"))+
    labs(x ="POLICIES", y = "Clark-Evans ind. <--min")

n_WT<-ggplot(pareto, aes(x=as.factor(POLICY), y=N_WT, fill = POLICY)) +   
    geom_boxplot()+
    facet_wrap(~RESTRICTION+MODEL_RUN)+
    #theme_light()+
    theme(legend.position = "none")+
    scale_fill_manual(values=c("#FF8000", "#00994D", "#0080ff","#ff33ff"))+
    labs(x ="POLICIES", y = "number of WT. <--min")+
    theme(axis.title.x = element_blank()) 
    
ener<-ggplot(pareto, aes(x=as.factor(POLICY), y=ENERDENS, fill = POLICY)) +   
    geom_boxplot()+
    facet_wrap(~RESTRICTION+MODEL_RUN)+
    #theme_light()+
    theme(legend.position = "none")+
    scale_fill_manual(values=c("#FF8000", "#00994D", "#0080ff","#ff33ff"))+
    labs(x ="POLICIES", y = "Energy density [MWh/yha]. --> max")+
    theme(axis.title.x = element_blank())

plot_tmp<-ggarrange(ener, n_WT, clus,  ncol = 1,nrow = 3, common.legend = T,labels = "auto")    
jpeg(file=paste("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/4_wp/descriptives/",paste(name,"_fitness_box.jpg",sep=""),sep=""),width = 1500, height = 2000)
plot(plot_tmp)
dev.off()


```
