---
title: "4b_Q1"
author: "R.Spielhofer"
date: "9 Dezember 2020"
output: html_document
---

```{r setup, include=FALSE}

require(raster)
require(rgdal)
require(dplyr)
require(sf)
require(sp)
require(ggplot2)
require(tmap)
require(tmaptools)
require(DBI)
require(RPostgreSQL)
require(rpostgis)
require(ggpubr)
require(spatstat)
require(rstatix)
require(reticulate)
require(tidyr)
require(maptools)
require(RPostgres)
require(stringr)
library(onewaytests)
library(psych)
library(plot3D)
library(coin)
```

#Load the pareto data
```{r}
cur_dat<-Sys.Date()
#here we import the best model runs for each
pareto<-read.csv("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/4_wp/fitness_selection_210113.csv", sep=",")

# by group, A = single relaxation, B = double, C = all
groupA<-subset(pareto, pareto$SCEN=="FOR"|pareto$SCEN=="ISOS"|pareto$SCEN=="CRF"|pareto$SCEN=="REF")

#B
groupB<-subset(pareto, pareto$GROUP=="B"|pareto$SCEN=="REF")

#C
groupC<-subset(pareto, pareto$SCEN=="ALL"|pareto$SCEN=="REF")
```

# Check data variance and distribution
```{r preconditions}
#1. CHECK FOR NORMAL DISTR
a<-as.data.frame(pareto %>%
  group_by(SCEN) %>%
  shapiro_test(ENERDENS))
write.csv(a, paste("Y:/people/spreto/01_ETH/02_PUBLICATIONS/01_MAIN/3_WIND_OPTIM/Tables/",paste(cur_dat,"shap_tmp.csv",sep="_"),sep=""))

#density plots per scen
ggplot(data=pareto, aes(x=ENERDENS, group=SCEN, fill=SCEN)) +
    geom_density(adjust=1.5)+ 
    facet_wrap(~SCEN) 
#homogeneity of variance
levene_test(tmp_dat,N_WT~SCEN,center = mean)
```

## and the appropriate test to compare the scenario means
```{r tests}

# if both not normal and inhomogeneity of variances == man whitney u test
#make comparison group manual
tmp_dat2<-subset(pareto,pareto$SCEN=="REF"|pareto$SCEN=="FOR")
tmp_dat2$SCEN<-as.factor(tmp_dat2$SCEN)

tmp_dat2 %>% 
rstatix::wilcox_test(CLUS ~ SCEN) %>%
add_significance()

 tmp_dat2 %>% 
wilcox_effsize(CLUS ~ SCEN)
 

tmp_dat2 %>% 
rstatix::wilcox_test(ENERDENS ~ SCEN) %>%
add_significance()

 tmp_dat2 %>% 
wilcox_effsize(ENERDENS ~ SCEN)
 

#◘if normal distributed but homogen variances == welch t.test
w<-welch.test(N_WT~SCEN,tmp_dat2)
paircomp(w)
#if both given == t.test
t.test(a$number_WT,b$number_WT,alternative = "two.sided", var.equal = FALSE)

```



```{r}
#######Box plots to explore the data of the three goals for each scenario
#order factor scen
pareto$SCEN <- factor(pareto$SCEN,levels = c("REF", "FOR", "CRF", "ISOS", "FOR_CRF", "FOR_ISOS", "ISOS_CRF","ALL"))

clus<-ggplot(pareto, aes(x=as.factor(SCEN), y=CLUS)) +   
    geom_boxplot()+
    theme_light()+
    theme(legend.position = "none",
        axis.text.y=element_text(size=14),
        axis.title.x=element_blank(),
        axis.text.x=element_blank())+
    labs(x ="SCENARIO", y = "Clustering [CE] <--min")

n_WT<-ggplot(pareto, aes(x=as.factor(SCEN), y=N_WT)) +   
    geom_boxplot()+
   theme_light()+
    theme(legend.position = "none",
        axis.text.y=element_text(size=14),
        axis.title.x=element_blank(),
        axis.text.x=element_blank())+
    labs(x ="SCENARIO", y = "Number of WT. <--min")
    
    
ener<-ggplot(pareto, aes(x=as.factor(SCEN), y=ENERDENS)) +   
    geom_boxplot()+
   theme_light()+
    theme(legend.position = "none",
          axis.text.x=element_text(size=14),
        axis.text.y=element_text(size=14),
              axis.title.x = element_blank())+
    labs(x ="SCENARIO", y = "Energy density [MWh/yha] --> max")

plot_tmp<-ggarrange( n_WT, clus, ener, ncol = 1,nrow = 3, common.legend = T,labels = "auto")    
jpeg(file=paste("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/4_wp/descriptives/",paste(cur_dat,"_fitness_box.jpg",sep=""),sep=""),width = 1500, height = 2000)
plot(plot_tmp)
dev.off()

```

