---
title: "4c_Q2"
author: "R.Spielhofer"
date: "9 Dezember 2020"
output: html_document
---

```{r setup, include=FALSE}
require(raster)
require(rgdal)
require(dplyr)
require(sf)
require(sp)
require(ggplot2)
require(tmap)
require(tmaptools)
require(DBI)
require(RPostgreSQL)
require(rpostgis)
require(ggpubr)
require(spatstat)
require(rstatix)
require(reticulate)
require(tidyr)
require(maptools)
require(RPostgres)
require(stringr)
library(onewaytests)
library(psych)
library(plot3D)
```


```{r}
###localhost
cur_dat<-Sys.Date()
pts<-st_read("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/4_wp/pts_sel_210112/FOR.shp")
bound<-st_read("Y:/people/spreto/2001_WIND_OPTIM/in/CH_Grenze.shp")
LT<-st_read("Y:/people/spreto/2001_WIND_OPTIM/in/LT3.shp")
bound<-st_transform(bound,crs = "+init=epsg:21781") 

dem<- raster("D:/04_PROJECTS/2001_WIND_OPTIM/in/dem_proj.tif")
# convert to a df for plotting in two steps,
# First, to a SpatialPointsDataFrame
DEM_pts <- rasterToPoints(dem, spatial = TRUE)
# Then to a 'conventional' dataframe
dem_df  <- data.frame(DEM_pts)
rm(DEM_pts, dem)

```

## maps of scenario pts for publication
```{r}
ggplot(data = bound) +
    geom_sf() +
    geom_sf(data = pts, color= "black", size=0.8)+
     geom_sf(data = bound, fill = NA, color = "gray")+
  theme_light()
  

```
# The important points per scenario
```{r}

## important robust pts

pts<-st_read("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/4_wp/pts_sel_210112/ALL.shp")
pts<-pts[order(-pts$par_rob),]
sum_prod = 0
ind=0

for(i in 1:nrow(pts)){
 if(sum_prod>4300000){
   break
   print(i)
  }
  tmp_prod<-pts$prod_MW[i]
  sum_prod<-sum_prod+tmp_prod
}
#create a subset to map  
rob_pts<-pts[1:i,]
```



# Spatial effects
```{r}
ppptmp<-as.ppp(rob_pts)

nndist<-mean(nndist(ppptmp))

#compute the spatial distribution of robust solution with CE index
#convert the pts in ppp and the polygon into owin in order to compute clark evans
b<-as(st_zm(bound), "Spatial")
y <- as(b, "SpatialPolygons")
LT_owin <- as.owin(y)
clarkevans(ppptmp, clipregion =  LT_owin)

ALTI<-mean(rob_pts$ALTI)
M_NDIST_HZ<-mean(rob_pts$DIST_HZ)
M_NDIST_ROAD<-mean(rob_pts$weigh_stre)


#here we can plot the 30 nearest neighbors and their average distances
#ANN <- apply(nndist(ppptmp, k=1:30),2,FUN=mean)
#plot(ANN ~ eval(1:30), type="b", main=NULL, las=1)

```
# number of WT in LT 
```{r}
dat<-as.data.frame(rob_pts)
dat$LT_char<-recode(dat$LT, 
                         `1`="Plat",
                         `2`="Alps",
                         `3`="Prealps")
dat %>% group_by(LT_char) %>% tally()

```



#density map for table with robust optimal
```{r}

ggplot(data = bound) +
    geom_sf(fill=NA) +
    geom_density_2d_filled(mapping = aes(x=st_coordinates(rob_pts)[,1] ,y=st_coordinates(rob_pts)[,2], fill = ..level..,  alpha = I(.6)), size = 1, bins = 6, data = rob_pts)+
  scale_fill_manual(values = c(NA, "grey70", "grey50","grey30", "grey15","grey5" ))+
  geom_sf(data = rob_pts, color="red", alpha = .2)+
     theme(panel.background = element_rect(fill = NA,
                                colour = NA,
                                size = 0.5, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'dashed',
                                colour = "grey70"),
        panel.grid.minor = element_blank(),
        # surpress legend
        legend.position = "none",
        axis.line=element_blank(),
        axis.text.x=element_text(size=18),
        axis.text.y=element_text(size=18),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())


```



## Distribution in landscape types
```{r}
#BARPLOT for LT distribution from csv
LT_WT<-read.csv("Y:/people/spreto/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/4_wp/LT_WT_210112.csv", sep=",")

LT_WT$SCENARIO <- factor(LT_WT$SCENARIO,levels = c("REF", "FOR", "CRF", "ISOS", "FOR_CRF", "FOR_ISOS", "ISOS_CRF","ALL"))


ggplot(data=LT_WT, aes(x=SCENARIO, y=N_WT, fill=LANDSCAPE_TYPE)) +
  geom_bar(stat="identity")+
  scale_fill_grey() + 
  ylab("Number of WT")+
  theme_light()+
  theme(axis.text.x=element_text(size=16),
        axis.text.y=element_text(size=16),
        legend.position = "bottom",
        legend.text = element_text(size =14))
 



```


# Trade off analysis

## 2D scatter plot
```{r}
pareto<-read.csv("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/4_wp/fitness_selection_210113.csv", sep=",")

tmp_dat<-subset(pareto,pareto$SCEN == "REF"| pareto$SCEN == "FOR"| pareto$SCEN == "ISOS" | pareto$SCEN == "CRF")

tmp_dat<-subset(pareto,pareto$GROUP == "B" | pareto$GROUP == "REF")
tmp_dat<-subset(pareto,pareto$GROUP == "A" | pareto$GROUP == "REF")


tmp_dat$SCEN<-as.factor(tmp_dat$SCEN)

num<-c(1,2,3,4)
tmp_dat$num<-num[as.factor(tmp_dat$SCEN)]


### trade off regression

A<-ggplot(tmp_dat, aes(x=N_WT, y=CLUS, group = SCEN)) + 
  geom_smooth(method=lm, se=FALSE, aes(color=SCEN, linetype = SCEN))+
  #scale_color_manual(values=c("#FF8000", "#0080ff", "#00994D", "#ff33ff", "red"))+
  scale_color_manual(values=c("#FF8000", "#a44a3f", "#a3b18a", "#0b090a", "red"))+
  scale_linetype_manual(values=c("longdash", "longdash","longdash","longdash","solid"))+
  geom_point(shape = 4, alpha = 0.1, size =0.1, color = "grey40")+
  labs(x ="min <-- N_WT", y = "Clark evans ind. <-- min")+
  theme_light()+
  theme(axis.text=element_text(size=16),
        axis.title=element_text(size=18),
        legend.text = element_text(size=20),
        legend.title = element_blank())
   


B<-ggplot(tmp_dat, aes(x=N_WT, y=ENERDENS, group = SCEN)) + 
geom_smooth(method=lm, se=FALSE, aes(color=SCEN, linetype = SCEN))+
  #scale_color_manual(values=c("#FF8000", "#0080ff", "#00994D", "#ff33ff", "red"))+
  scale_color_manual(values=c("#FF8000", "#a44a3f", "#a3b18a", "#0b090a", "red"))+
  scale_linetype_manual(values=c("longdash", "longdash","longdash","longdash","solid"))+
  geom_point(shape = 4, alpha = 0.1, size =0.1, color = "grey40")+
    labs(x ="min <-- N_WT",y="energy density [MWh/yha]--> max")+
 theme_light()+
  theme(axis.text=element_text(size=16),
        axis.title=element_text(size=18))

C<-ggplot(tmp_dat, aes(x=CLUS, y=ENERDENS, group = SCEN)) + 
geom_smooth(method=lm, se=FALSE, aes(color=SCEN, linetype = SCEN))+
  #scale_color_manual(values=c("#FF8000", "#0080ff", "#00994D", "#ff33ff", "red"))+
  scale_color_manual(values=c("#FF8000", "#a44a3f", "#a3b18a", "#0b090a", "red"))+
  scale_linetype_manual(values=c("longdash", "longdash","longdash","longdash","solid"))+
  geom_point(shape = 4, alpha = 0.1, size =0.1, color = "grey40")+
    labs(y ="min <-- Clark evans ind.", x = "energy density [MWh/yha] --> max")+
 theme_light()+
  theme(axis.text=element_text(size=16),
        axis.title=element_text(size=18))
cur_dat<-Sys.Date()

plot_tmp<-ggarrange(A, B, C, ncol = 1,nrow = 3, common.legend = T) 

#plot(plot_tmp)

```


## 3D Pareto front
```{r}

scatter3d(tmp_dat$N_WT, tmp_dat$CLUS, tmp_dat$ENERDENS,
          xlab = "min<--N_WT",
          ylab ="min<--CLUSTER", 
          zlab = "max<--ENERDENSx",
          groups = tmp_dat$SCENARIO,
          surface = F,
          axis.scales = T,
          axis.ticks = T,
          ellipsoid = T,
          sphere.size = T)

# Add small dots on basal plane and on the depth plane
scatter3D_fancy <- function(x, y, z,..., colvar = colvar)
  {
   panelfirst <- function(pmat) {
      XY <- trans3D(x, y, z = rep(min(z), length(z)), pmat = pmat)
      scatter2D(XY$x, XY$y, col = "#999999", pch = ".", 
              cex = 0.1, add = TRUE, colkey = FALSE)
   
      XY <- trans3D(x = rep(min(x), length(x)), y, z, pmat = pmat)
      scatter2D(XY$x, XY$y, col = "#999999", pch = ".", 
              cex = 0.1, add = TRUE, colkey = FALSE)
  }
  scatter3D(x, y, z, ..., colvar = colvar, panel.first=panelfirst) 
}



jpeg(file=paste("D:/04_PROJECTS/2001_WIND_OPTIM/WIND_OPTIM_git/intermediate_steps/4_wp/",paste(cur_dat,"3D_single.jpg",sep="_"),sep=""),width = 1200, height = 1200)
scatter3D_fancy(tmp_dat$N_WT, tmp_dat$CLUS, tmp_dat$ENERDENS,
          colvar = as.integer(tmp_dat$num),
          col = c("#FF8000", "#0080ff", "#00994D","#ff33ff"),
          xlab = "min<--N_WT",
          ylab ="min<--CLUSTER", 
          zlab = "max<--ENERDENS",
          theta = 25,d = 1, phi = 0, cex=0.3, bty = "b2",ticktype = "detailed",colkey = list(at = c(1,2, 3, 4), side = 1, 
          addlines = TRUE, length = 0.5, width = 0.5,
          labels = as.vector(levels(tmp_dat$SCEN))))
dev.off()
   

 theme(axis.text=element_text(size=16),
        axis.title=element_text(size=18),
        legend.text = element_text(size=20),
        legend.title = element_blank())
           
```
